### ISSUE TITLE
这个例子能详细说说吗?

### ISSUE THREAD

**Issue by yuanb07** [HKUDS/SimRec#2]
![image](https://github.com/HKUDS/SimRec/assets/74127982/c2f7e9c5-f124-4a44-b78e-eb0e622271ac)

**Comment by akaxlh** [comment]
你好，感谢对我们工作的关注。
这个例子来自于yelp数据集，这个数据集包含了用户和商店、餐馆、汽修店等多类经营性场所之间的交互记录。u_1269和u_13790是一对二跳邻居，GNN会认为这样的用户在偏好方面有较高的相似度。但这两个用户实际上只是都入住过Las Vegas的一家大型酒店。通过检查他们各自的其他交互，我们发现，u_1269喜欢快餐店、酒吧，而u_13790喜欢购物、手工，在实际偏好上存在明显的不同。
在这幅图片下方，展示了GNN模型和MLP模型对两者关系的预测，GNN给出了0.75的高cosine相似度，MLP则明显降低，为0.61。颜色方格展示了两个模型对两个用户给出的一共四个embedding，可以看到GNN teacher对两者的embedding十分相似，仅框出的两个维度有明显较大的差别，而MLP的embedding则差异非常明显。
